<?php
/**
 * product_data.php — Complete product catalog (40 products)
 * Each product has: id, name, cat, price, oldPrice, images[], shortDetail
 */

$PRODUCTS = [
    // ═══════════════════════════════════════
    // CLASSIC COLLECTION (1-8)
    // ═══════════════════════════════════════
    [
        'id' => 'p1',
        'name' => 'Khalid Classic Brown',
        'cat' => 'classic',
        'price' => 1800,
        'oldPrice' => 2200,
        'images' => ['uploads/products/1.1.png', 'uploads/products/1.2.png', 'uploads/products/1.3.png'],
        'shortDetail' => 'Hand-stitched pure leather with durable rubber sole. Timeless Peshawari design for everyday wear.',
    ],
    [
        'id' => 'p2',
        'name' => 'Shahi Beige Suede',
        'cat' => 'casual',
        'price' => 2200,
        'oldPrice' => 2800,
        'images' => ['uploads/products/2.1.png', 'uploads/products/2.2.png', 'uploads/products/2.3.png'],
        'shortDetail' => 'Soft suede leather with brass buckle strap. Lightweight and comfortable for casual outings.',
    ],
    [
        'id' => 'p3',
        'name' => 'Royal Black Premium',
        'cat' => 'premium',
        'price' => 2800,
        'oldPrice' => 3400,
        'images' => ['uploads/products/3.1.png', 'uploads/products/3.2.png', 'uploads/products/3.3.png'],
        'shortDetail' => 'Glossy black leather with gold buckle and white contrast stitching. Statement piece for formal events.',
    ],
    [
        'id' => 'p4',
        'name' => 'Peshawari Camel',
        'cat' => 'classic',
        'price' => 1600,
        'oldPrice' => 2000,
        'images' => ['uploads/products/4.1.png', 'uploads/products/4.2.png', 'uploads/products/4.3.png'],
        'shortDetail' => 'Traditional camel tone leather with sturdy rubber sole. Authentic Peshawari craftsmanship.',
    ],
    [
        'id' => 'p5',
        'name' => 'Shahi Tan Classic',
        'cat' => 'classic',
        'price' => 1900,
        'oldPrice' => 2400,
        'images' => ['uploads/products/5.1.png', 'uploads/products/5.2.png', 'uploads/products/5.3.png', 'uploads/products/5.4.png'],
        'shortDetail' => 'Rich tan leather with cross-strap design and brass buckle. Perfect blend of tradition and comfort.',
    ],
    [
        'id' => 'p6',
        'name' => 'Khalid Dark Brown',
        'cat' => 'classic',
        'price' => 1700,
        'oldPrice' => 2100,
        'images' => ['uploads/products/6.1.png', 'uploads/products/6.2.png', 'uploads/products/6.3.png'],
        'shortDetail' => 'Deep chocolate brown leather with traditional cross pattern. Durable everyday chappal.',
    ],
    [
        'id' => 'p7',
        'name' => 'Premium Brown Elite',
        'cat' => 'premium',
        'price' => 3200,
        'oldPrice' => 3900,
        'images' => ['uploads/products/7.1.png', 'uploads/products/7.2.png', 'uploads/products/7.3.png'],
        'shortDetail' => 'Hand-polished brown leather with silver buckle. Premium finish for special occasions.',
    ],
    [
        'id' => 'p8',
        'name' => 'Shahi Black Gold',
        'cat' => 'premium',
        'price' => 3500,
        'oldPrice' => 4200,
        'images' => ['uploads/products/8.1.png', 'uploads/products/8.2.png', 'uploads/products/8.3.png'],
        'shortDetail' => 'Matte black leather with gold-tone buckle accent. Luxurious design for the modern gentleman.',
    ],

    // ═══════════════════════════════════════
    // PREMIUM COLLECTION (9-16)
    // ═══════════════════════════════════════
    [
        'id' => 'p9',
        'name' => 'Peshawari Ebony',
        'cat' => 'premium',
        'price' => 3000,
        'oldPrice' => 3600,
        'images' => ['uploads/products/9.1.png', 'uploads/products/9.2.png'],
        'shortDetail' => 'Solid ebony black leather with classic cross-strap. Refined elegance for formal gatherings.',
    ],
    [
        'id' => 'p10',
        'name' => 'Royal Gloss Black',
        'cat' => 'premium',
        'price' => 3800,
        'oldPrice' => 4500,
        'images' => ['uploads/products/10.1.png', 'uploads/products/10.2.png', 'uploads/products/10.3.png'],
        'shortDetail' => 'Mirror-finish black leather with silver buckle. High-shine premium chappal for weddings.',
    ],
    [
        'id' => 'p11',
        'name' => 'Khalid Brown Classic',
        'cat' => 'classic',
        'price' => 1850,
        'oldPrice' => 2300,
        'images' => ['uploads/products/11.1.png', 'uploads/products/11.2.png', 'uploads/products/11.3.png'],
        'shortDetail' => 'Heritage brown leather with hand-carved details. Classic Peshawari style for daily wear.',
    ],
    [
        'id' => 'p12',
        'name' => 'Shahi Maroon Elite',
        'cat' => 'premium',
        'price' => 3400,
        'oldPrice' => 4100,
        'images' => ['uploads/products/12.1.png', 'uploads/products/12.2.png', 'uploads/products/12.3.png'],
        'shortDetail' => 'Deep maroon leather with gold buckle. Rich color for festive and wedding occasions.',
    ],
    [
        'id' => 'p13',
        'name' => 'Premium Tan Deluxe',
        'cat' => 'premium',
        'price' => 3100,
        'oldPrice' => 3800,
        'images' => ['uploads/products/13.1.png', 'uploads/products/13.2.png', 'uploads/products/13.3.png'],
        'shortDetail' => 'Double-stitched tan leather with comfort insole. Premium quality for discerning buyers.',
    ],
    [
        'id' => 'p14',
        'name' => 'Peshawari Copper',
        'cat' => 'premium',
        'price' => 3600,
        'oldPrice' => 4300,
        'images' => ['uploads/products/14.1.png', 'uploads/products/14.2.png', 'uploads/products/14.3.png'],
        'shortDetail' => 'Copper-toned leather with antique buckle finish. Unique color for standout style.',
    ],
    [
        'id' => 'p15',
        'name' => 'Shahi Honey Gold',
        'cat' => 'classic',
        'price' => 2100,
        'oldPrice' => 2600,
        'images' => ['uploads/products/15.1.png', 'uploads/products/15.2.png', 'uploads/products/15.3.png'],
        'shortDetail' => 'Warm honey-toned leather with brass buckle. Smooth finish for elegant everyday wear.',
    ],
    [
        'id' => 'p16',
        'name' => 'Royal Walnut',
        'cat' => 'premium',
        'price' => 3300,
        'oldPrice' => 4000,
        'images' => ['uploads/products/16.1.png', 'uploads/products/16.2.png', 'uploads/products/16.3.png'],
        'shortDetail' => 'Rich walnut brown with hand-finished edges. Sophisticated choice for formal events.',
    ],

    // ═══════════════════════════════════════
    // CASUAL COLLECTION (17-24)
    // ═══════════════════════════════════════
    [
        'id' => 'p17',
        'name' => 'Khalid Casual Black',
        'cat' => 'casual',
        'price' => 1500,
        'oldPrice' => 1900,
        'images' => ['uploads/products/17.1.png', 'uploads/products/17.2.png', 'uploads/products/17.3.png'],
        'shortDetail' => 'Everyday black leather with rubber sole. Comfortable and affordable for daily use.',
    ],
    [
        'id' => 'p18',
        'name' => 'Shahi Sand Beige',
        'cat' => 'casual',
        'price' => 1650,
        'oldPrice' => 2100,
        'images' => ['uploads/products/18.1.png', 'uploads/products/18.2.png', 'uploads/products/18.3.png'],
        'shortDetail' => 'Lightweight beige leather with ankle strap. Perfect for summer casuals.',
    ],
    [
        'id' => 'p19',
        'name' => 'Peshawari Olive',
        'cat' => 'casual',
        'price' => 1800,
        'oldPrice' => 2300,
        'images' => ['uploads/products/19.1.png', 'uploads/products/19.2.png', 'uploads/products/19.3.png'],
        'shortDetail' => 'Unique olive green suede with leather trim. Trendy casual chappal for young men.',
    ],
    [
        'id' => 'p20',
        'name' => 'Shahi Textured Black',
        'cat' => 'premium',
        'price' => 2900,
        'oldPrice' => 3500,
        'images' => ['uploads/products/20.1.png', 'uploads/products/20.2.png', 'uploads/products/20.3.png'],
        'shortDetail' => 'Pebbled texture black leather with gold buckle. Distinctive look for style-conscious buyers.',
    ],
    [
        'id' => 'p21',
        'name' => 'Classic Caramel',
        'cat' => 'classic',
        'price' => 1950,
        'oldPrice' => 2500,
        'images' => ['uploads/products/21.1.png', 'uploads/products/21.2.png', 'uploads/products/21.3.png'],
        'shortDetail' => 'Warm caramel leather with cross-strap design. Traditional charm with modern comfort.',
    ],
    [
        'id' => 'p22',
        'name' => 'Khalid Espresso',
        'cat' => 'classic',
        'price' => 1750,
        'oldPrice' => 2200,
        'images' => ['uploads/products/22.1.png', 'uploads/products/22.2.png', 'uploads/products/22.3.png'],
        'shortDetail' => 'Deep espresso brown leather with contrast stitching. Rich color for a refined look.',
    ],
    [
        'id' => 'p23',
        'name' => 'Shahi Cognac',
        'cat' => 'casual',
        'price' => 1600,
        'oldPrice' => 2000,
        'images' => ['uploads/products/23.1.png', 'uploads/products/23.2.png', 'uploads/products/23.3.png'],
        'shortDetail' => 'Cognac-toned leather with cutout design. Breathable and stylish for warm weather.',
    ],
    [
        'id' => 'p24',
        'name' => 'Premium Mocha',
        'cat' => 'premium',
        'price' => 2700,
        'oldPrice' => 3300,
        'images' => ['uploads/products/24.1.png', 'uploads/products/24.2.png', 'uploads/products/24.3.png'],
        'shortDetail' => 'Smooth mocha leather with dual-buckle strap. Refined casual luxury.',
    ],

    // ═══════════════════════════════════════
    // MODERN COLLECTION (25-32)
    // ═══════════════════════════════════════
    [
        'id' => 'p25',
        'name' => 'Shahi Forest Green',
        'cat' => 'modern',
        'price' => 2500,
        'oldPrice' => 3100,
        'images' => ['uploads/products/25.1.png', 'uploads/products/25.2.png', 'uploads/products/25.3.png'],
        'shortDetail' => 'Forest green suede with leather accents. Bold color for the fashion-forward gentleman.',
    ],
    [
        'id' => 'p26',
        'name' => 'Khalid Slate Grey',
        'cat' => 'modern',
        'price' => 2300,
        'oldPrice' => 2900,
        'images' => ['uploads/products/26.1.png', 'uploads/products/26.2.png', 'uploads/products/26.3.png'],
        'shortDetail' => 'Slate grey leather with minimalist design. Contemporary style meets tradition.',
    ],
    [
        'id' => 'p27',
        'name' => 'Peshawari Indigo',
        'cat' => 'modern',
        'price' => 2600,
        'oldPrice' => 3200,
        'images' => ['uploads/products/27.1.png', 'uploads/products/27.2.png', 'uploads/products/27.3.png'],
        'shortDetail' => 'Deep indigo leather with contrast sole. Modern interpretation of classic Peshawari.',
    ],
    [
        'id' => 'p28',
        'name' => 'Shahi Burgundy',
        'cat' => 'modern',
        'price' => 2800,
        'oldPrice' => 3400,
        'images' => ['uploads/products/28.1.png', 'uploads/products/28.2.png', 'uploads/products/28.3.png'],
        'shortDetail' => 'Rich burgundy leather with antique brass buckle. Statement piece for festive occasions.',
    ],
    [
        'id' => 'p29',
        'name' => 'Premium Charcoal',
        'cat' => 'modern',
        'price' => 2400,
        'oldPrice' => 3000,
        'images' => ['uploads/products/29.1.png', 'uploads/products/29.2.png', 'uploads/products/29.3.png'],
        'shortDetail' => 'Charcoal matte leather with sleek profile. Understated elegance for modern men.',
    ],
    [
        'id' => 'p30',
        'name' => 'Classic Heritage Brown',
        'cat' => 'classic',
        'price' => 2000,
        'oldPrice' => 2500,
        'images' => ['uploads/products/30.1.png', 'uploads/products/30.2.png', 'uploads/products/30.3.png'],
        'shortDetail' => 'Heritage brown with brass buckle and embossed footbed. Timeless classic reimagined.',
    ],
    [
        'id' => 'p32',
        'name' => 'Khalid Midnight Blue',
        'cat' => 'modern',
        'price' => 2700,
        'oldPrice' => 3300,
        'images' => ['uploads/products/32.1.png', 'uploads/products/32.2.png', 'uploads/products/32.3.png'],
        'shortDetail' => 'Midnight blue leather with white contrast stitching. Contemporary color for evening wear.',
    ],

    // ═══════════════════════════════════════
    // UNIQUE COLLECTION (33-41)
    // ═══════════════════════════════════════
    [
        'id' => 'p33',
        'name' => 'Shahi Two-Tone',
        'cat' => 'modern',
        'price' => 2900,
        'oldPrice' => 3500,
        'images' => ['uploads/products/33.1.png', 'uploads/products/33.2.png', 'uploads/products/33.3.png'],
        'shortDetail' => 'Dual-tone brown and tan leather. Unique color block design for fashion enthusiasts.',
    ],
    [
        'id' => 'p34',
        'name' => 'Peshawari Sand',
        'cat' => 'casual',
        'price' => 1400,
        'oldPrice' => 1800,
        'images' => ['uploads/products/34.1.png', 'uploads/products/34.2.png', 'uploads/products/34.3.png'],
        'shortDetail' => 'Light sand leather with open design. Breezy comfort for summer days.',
    ],
    [
        'id' => 'p35',
        'name' => 'Khalid Cutout Tan',
        'cat' => 'casual',
        'price' => 1550,
        'oldPrice' => 2000,
        'images' => ['uploads/products/35.1.png', 'uploads/products/35.2.png'],
        'shortDetail' => 'Tan leather with artistic cutout pattern. Breathable and eye-catching design.',
    ],
    [
        'id' => 'p36',
        'name' => 'Shahi Umber',
        'cat' => 'classic',
        'price' => 1900,
        'oldPrice' => 2400,
        'images' => ['uploads/products/36.1.png', 'uploads/products/36.2.png'],
        'shortDetail' => 'Deep umber brown leather with padded insole. Comfort meets classic style.',
    ],
    [
        'id' => 'p37',
        'name' => 'Premium Espresso Duo',
        'cat' => 'premium',
        'price' => 3000,
        'oldPrice' => 3700,
        'images' => ['uploads/products/37.1.png', 'uploads/products/37.2.png'],
        'shortDetail' => 'Dual-shade espresso leather with handcrafted stitching. Artisanal premium quality.',
    ],
    [
        'id' => 'p38',
        'name' => 'Khalid Rust',
        'cat' => 'casual',
        'price' => 1500,
        'oldPrice' => 1900,
        'images' => ['uploads/products/38.1.png', 'uploads/products/38.2.png'],
        'shortDetail' => 'Rust-toned leather with adjustable strap. Warm earthy color for casual outings.',
    ],
    [
        'id' => 'p39',
        'name' => 'Shahi Camel Luxe',
        'cat' => 'premium',
        'price' => 2600,
        'oldPrice' => 3200,
        'images' => ['uploads/products/39.1.png', 'uploads/products/39.2.png'],
        'shortDetail' => 'Luxurious camel leather with gold hardware. Refined elegance for special events.',
    ],
    [
        'id' => 'p40',
        'name' => 'Classic Tan Slide',
        'cat' => 'casual',
        'price' => 1200,
        'oldPrice' => 1600,
        'images' => ['uploads/products/40.1.png', 'uploads/products/40.2.png'],
        'shortDetail' => 'Open-toe slide design in smooth tan leather. Effortless slip-on comfort.',
    ],
    [
        'id' => 'p41',
        'name' => 'Shahi Caramel Open',
        'cat' => 'casual',
        'price' => 1350,
        'oldPrice' => 1750,
        'images' => ['uploads/products/41.1.png', 'uploads/products/41.2.png'],
        'shortDetail' => 'Caramel leather with open-toe and cutout design. Summer-ready casual chappal.',
    ],
];
